apiDir: "../restbuilder-api/src/main/java"
apiPackagePath: "com.liferay.rest"
application:
    baseURI: "/restbuilder"
    className: "RestbuilderApplication"
    name: "Restbuilder"
author: "wos"
clientDir: "../restbuilder-client/src/main/java"
testDir: "../restbuilder-test/src/testIntegration/java"